title: "Espy Yonder"
author: "pruthuvi maheshakya wijewardena"
description: "maheshakyas' personal website"
subheading: "maheshakyas' personal website"
more: "read more"
url: "https://www.facebook.com/pmaheshakya"
baseurl: "/maheshakya.wijewardena" # comment out if in root directory

comments:
    disqus: "maheshakya"
#    isso: "comments.mysite.org"

style:
#    body: "whitesmoke"
    padding: 33%
    anchor: "#46f"
    serif-heading: true
    nav: "#181818"
#    headline: "#06f"
    description: "white"
    article:
        odd: "#ffffff"
        even: "#222222"

links:
  - github: "https://github.com/maheshakya"
  - twitter: "https://twitter.com/Wmaheshakya"
  - google-plus: "https://plus.google.com/u/0/+MaheshakyaWijewardena/"
  - youtube: "https://www.youtube.com/channel/UCGCNlASS-LWH8PYd1Me5-Zg/feed"

excerpt_separator: "\n\n\n"
defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
