port: 40000
auto: true
safe: true
server: true
pygments: true
markdown: redcarpet

#permalinks
permalinks: pretty

name: Espy Yonder
description: This is my personal blog created in order to espy yonder 
url: http://maheshakya.github.io/

category: [GSoC, Other]